apiVersion: v1 
kind: Pod 
metadata: 
      name: node-mode-selector 
      labels: 
        env: test 
spec: 
    containers: 
    - name: nginx 
      image: nginx 
      imagePullPolicy: Always 
      nodeSelector:
           disktype: ssd         
