apiVersion: v1 
kind: Pod 
metadata: 
      name: node-selector-demo-1 
      labels: 
         env: test 
spec: 
   containers: 
   - name: nginx 
     image: nginx 
   nodeSelector: 
       disktype: ssd             