apiVersion: v1 
kind: Pod 
metadata: 
      name: with-node-affinity 
spec: 
   affinity: 
      nodeAfiinity: 
        requiredDuringSchedulingIgnoredDuringExecution: 
          nodeSelectorTerms: 
          - matchExpressions: 
            - key: hardware 
              operator: In 
              values: 
              - gpu        
