apiVersion: v1 
kind: Pod 
metadata: 
    name: with-node-affinity 
spec: 
   affinity: 
      nodeAffinity: 
         requiredDuringSchedulingIgnoreDuringExecution: 
          nodeSelectorTerms:
          - matchExpressions: 
            - key: hardware 
              operator: In 
              values: 
              - gpu 
        #  preferredDuringSchedulingIgnoreDuringExecution: 
        #  - weight: 1 
        #    preference: 
        #      matchExpressions: 
        #      - key: another-node-label-key 
        #        operator: In 
        #        values:
        #        - another-node-label-value 
   containers: 
   - name: with-node-affinity 
     image: nginx              
                            