apiVersion: v1 
kind: Pod 
metadata: 
       name: with-node-anti-affinity 
spec: 
   affinity:
     nodeAffinity: 
       requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectors: 
        - matchExpressions: 
          - key: hardware 
            operator: NotIn 
            values: 
            - gpu 
   containers: 
   - name: with-node-anti-affinity 
     image: nginx       