apiVersion: apps/v1 
kind: Deployment 
metadata: 
      name: redis-cache 
spec: 
   selector: 
         matchLabels: 
             app: store 
   repliacas:
   template: 
        metadata: 
            labels: 
                app: store 
        spec: 
           affinity: 
              podAntiAffinity: 
                  requiredDuringSchedulingIgnoredDuringExecution: 
                  - labelSelector: 
                      matchExpressions: 
                      - key: app 
                        operator: In 
                        values: 
                        - pod-1 
                    topologyKey: "kubernetes.io/hostname" 
           containers: 
           - name: redis-server 
             image: redis:3.2-alpine                                            

